package com.tendril.app.data

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import androidx.room.TypeConverters
import androidx.sqlite.SQLiteDriver
import com.tendril.app.data.canvas.CanvasEdge
import com.tendril.app.data.canvas.CanvasEdgeDao
import com.tendril.app.data.canvas.CanvasNode
import com.tendril.app.data.canvas.CanvasNodeDao
import com.tendril.app.data.canvas.PageCanvas
import com.tendril.app.data.canvas.PageCanvasDao
import com.tendril.app.data.completion.EntryCompletion
import com.tendril.app.data.completion.EntryCompletionDao
import com.tendril.app.data.entry.Entry
import com.tendril.app.data.entry.EntryDao
import com.tendril.app.data.habit.Habit
import com.tendril.app.data.habit.HabitDao
import com.tendril.app.data.page.Block
import com.tendril.app.data.page.BlockDao
import com.tendril.app.data.page.Page
import com.tendril.app.data.page.PageDao
import com.tendril.app.data.page.PageFtsDao
import com.tendril.app.data.page.PageFtsEntry
import com.tendril.app.data.page.PageRelation
import com.tendril.app.data.page.PageRelationDao
import com.tendril.app.data.page.PageTag
import com.tendril.app.data.page.Tag
import com.tendril.app.data.page.TagDao
import com.tendril.app.data.pagedatabase.PageDatabase
import com.tendril.app.data.pagedatabase.PageDatabaseDao
import com.tendril.app.data.pagedatabase.PageDatabaseView
import com.tendril.app.data.pagedatabase.PageDatabaseViewDao
import com.tendril.app.data.pagedatabase.Property
import com.tendril.app.data.pagedatabase.PropertyDao
import com.tendril.app.data.pagedatabase.PropertyValue
import com.tendril.app.data.pagedatabase.PropertyValueDao
import com.tendril.app.data.reminder.Reminder
import com.tendril.app.data.reminder.ReminderDao
import kotlinx.coroutines.Dispatchers

/**
 * §9.10 (Decided 2026-08-26) — Room migration policy: `fallbackToDestructiveMigration()`
 * pre-v1 (Phases 1–7, current), since nothing stored yet is anything but trivially
 * re-creatable and the schema is still visibly moving. Post-v1 switches to
 * `@AutoMigration` + manual fallback + snapshot-backed recovery — not relevant until this
 * app is in real daily use, tracked here as a forward pointer rather than acted on now.
 *
 * §12.5 — moved into `:shared` (KMP): the platform-specific builder (`Context` on Android,
 * a file path on desktop) lives in each target's own source set; `@ConstructedBy` lets Room's
 * KSP codegen supply the per-platform constructor Room needs to build this class outside of
 * Android's Context-bound APIs.
 */
@Database(
    entities = [
        Entry::class, Habit::class, Reminder::class, EntryCompletion::class,
        Page::class, Tag::class, PageTag::class, Block::class, PageFtsEntry::class,
        PageDatabase::class, Property::class, PropertyValue::class, PageDatabaseView::class,
        PageRelation::class, PageCanvas::class, CanvasNode::class, CanvasEdge::class,
    ],
    version = 5, // §3.2/§9.9 — Entry.providerEventId added; destructive pre-v1 migration (§9.10)
    // No schema-history export while Room migration policy is destructive-only pre-v1
    // (§9.10) — nothing to diff against yet. Revisit alongside the @AutoMigration switch.
    exportSchema = false,
)
@TypeConverters(Converters::class)
@ConstructedBy(TendrilDatabaseConstructor::class)
abstract class TendrilDatabase : RoomDatabase() {
    abstract fun entryDao(): EntryDao
    abstract fun habitDao(): HabitDao
    abstract fun reminderDao(): ReminderDao
    abstract fun entryCompletionDao(): EntryCompletionDao

    abstract fun pageDao(): PageDao
    abstract fun tagDao(): TagDao
    abstract fun blockDao(): BlockDao
    abstract fun pageFtsDao(): PageFtsDao
    abstract fun pageDatabaseDao(): PageDatabaseDao
    abstract fun propertyDao(): PropertyDao
    abstract fun propertyValueDao(): PropertyValueDao
    abstract fun pageDatabaseViewDao(): PageDatabaseViewDao
    abstract fun pageRelationDao(): PageRelationDao
    abstract fun pageCanvasDao(): PageCanvasDao
    abstract fun canvasNodeDao(): CanvasNodeDao
    abstract fun canvasEdgeDao(): CanvasEdgeDao
}

// expect object, actual generated by Room's KSP codegen per target — not hand-written.
expect object TendrilDatabaseConstructor : RoomDatabaseConstructor<TendrilDatabase>

/** Shared finish-and-build step; each platform's own `buildTendrilDatabase` supplies the driver. */
internal fun finishBuilding(
    builder: RoomDatabase.Builder<TendrilDatabase>,
    driver: SQLiteDriver,
): TendrilDatabase =
    builder
        .setDriver(driver)
        .setQueryCoroutineContext(Dispatchers.IO)
        .fallbackToDestructiveMigration(dropAllTables = true) // §9.10 pre-v1 policy
        .build()
